#ifndef __DESKTOP_WORMS_SRC_CLIENT_CLIENT_CONSTANTS_H_
#define __DESKTOP_WORMS_SRC_CLIENT_CLIENT_CONSTANTS_H_

// Graphics
#define SCREEN_WIDTH 640
#define SCREEN_HEIGHT 480

#define LEVEL_WIDTH 1000
#define LEVEL_HEIGHT 1000

#define PPM 1000 / 20

#endif  // __DESKTOP_WORMS_SRC_CLIENT_CLIENT_CONSTANTS_H_
